# Generated by Django 6.0.3 on 2026-03-15 00:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contest_contestentry_contest_winner_contestvote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('first_post', '✍️ First Echo'), ('ten_posts', '📚 Prolific Writer'), ('fifty_posts', '🏆 Master Storyteller'), ('first_like', '❤️ First Like'), ('hundred_likes', '💫 Beloved Writer'), ('first_comment', '💬 Conversationalist'), ('streak_7', '🔥 7-Day Streak'), ('streak_30', '⚡ 30-Day Streak'), ('contest_entry', '🎯 Contest Participant'), ('contest_winner', '👑 Contest Winner'), ('collab_story', '🤝 Collaborator'), ('word_challenge', '📖 Word Challenger')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='mood',
            field=models.CharField(blank=True, choices=[('melancholic', '😔 Melancholic'), ('hopeful', '🌟 Hopeful'), ('funny', '😄 Funny'), ('tense', '😰 Tense'), ('romantic', '❤️ Romantic'), ('inspiring', '✨ Inspiring'), ('reflective', '🤔 Reflective'), ('dark', '🌑 Dark')], max_length=20),
        ),
        migrations.CreateModel(
            name='CollaborativeStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open for contributions'), ('closed', 'Closed')], default='open', max_length=10)),
                ('max_contributors', models.IntegerField(default=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Collaborative Stories',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PromptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_responses', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='blog.dailyprompt')),
            ],
            options={
                'ordering': ['-created_date'],
                'unique_together': {('prompt', 'author')},
            },
        ),
        migrations.CreateModel(
            name='WordOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Word of the Day',
                'verbose_name_plural': 'Words of the Day',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WordOfTheDayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_entries', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='blog.wordoftheday')),
            ],
            options={
                'ordering': ['-created_date'],
                'unique_together': {('word', 'author')},
            },
        ),
        migrations.CreateModel(
            name='WritingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=25)),
                ('words_written', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='WritingStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_post_date', models.DateField(blank=True, null=True)),
                ('total_posts', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('alltime', 'All Time')], max_length=10)),
                ('category', models.CharField(choices=[('most_liked', 'Most Liked Writer'), ('most_active', 'Most Active Commenter'), ('most_posts', 'Most Posts'), ('contest_wins', 'Contest Wins')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('user', 'period', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PromptResponseLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.promptresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_response_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('response', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoryParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_paragraphs', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='blog.collaborativestory')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('story', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='WordEntryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_entry_likes', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.wordofthedayentry')),
            ],
            options={
                'unique_together': {('entry', 'user')},
            },
        ),
    ]
