# Generated by Django 6.0.3 on 2026-03-23 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_badge_post_mood_collaborativestory_dailyprompt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("stats", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
    ]
