# Generated by Django 6.0.3 on 2026-04-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_notification_friend_friendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_ai",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="persona_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
