# Generated by Django 6.0.3 on 2026-04-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_userprofile_is_ai_userprofile_persona_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="ai_summary",
            field=models.TextField(
                blank=True, help_text="AI-generated 1-sentence summary"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="toxicity_score",
            field=models.FloatField(default=0.0),
        ),
    ]
