# Generated by Django 6.0.3 on 2026-04-11 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_comment_is_flagged_post_ai_summary_post_is_flagged_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                default="#7c3aed", help_text="Brand color hex code", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                default="fas fa-circle",
                help_text="FontAwesome class (e.g., 'fas fa-feather')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribed_circles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
