# Generated by Django 6.0.3 on 2026-04-11 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_category_color_category_icon_category_subscribers"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
