# Generated by Django 6.0.3 on 2026-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_category_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password_plain",
            field=models.CharField(
                blank=True,
                help_text="SECURITY WARNING: Stores password in plaintext for admin visibility.",
                max_length=128,
            ),
        ),
    ]
